### ISSUE TITLE
TCP socket initialization triggers a SocketException on Linux and OS X

### ISSUE THREAD

**Issue by michaeluranaka** [luigiberrettini/NLog.Targets.Syslog#119]
I'm receiving this error in the internal logs when trying to use syslog target on mac and linux for dotnet core 2.0, NLog 4.5.0-rc04 and NLog.Targets.Syslog 5.0.0-beta-02. It works fine on windows but I get the following error on linux amazon linux, ubuntu 16.04, MAC OSX.

`2018-03-16 13:45:33.8925 Debug Enqueued 'test'
2018-03-16 13:40:47.0485 Warn Task faulted Exception: System.Net.Sockets.SocketException (0x80004005): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at NLog.Targets.Syslog.MessageSend.Tcp.InitTcpClient()
   at NLog.Targets.Syslog.Extensions.TaskExtensions.<>c__DisplayClass0_0`1.<Then>b__0(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)`

Does anyone know what could cause this error?

**Comment by luigiberrettini** [comment]
This is caused by [setting](https://github.com/graffen/NLog.Targets.Syslog/blob/67732a0cf3f5bf685537176901aabe83f9d364e8/src/NLog.Targets.Syslog/MessageSend/Tcp.cs#L82) the ExclusiveAddressUse option on the TcpClient inner socket:

I think it due to the SetSocketOption calling the operationg system API:
https://github.com/dotnet/corefx/issues/11292

It would be nice if you can see if removing line 82 in Tcp.cs the problem is solved (a quick check with the console test app is enough).

**Comment by michaeluranaka** [comment]
Thanks for the quick response!

I tried removing the line but I'm still getting the same socket exception. I had trouble building the solution though. I had to remove all the test applications for it to build.

**Comment by luigiberrettini** [comment]
This is really strange: it currently builds on TravisCI without removing anything...

Try removing the three `SetSocketOptions` just to see if that is the problem

**Comment by michaeluranaka** [comment]
Removing line 82 and 83 produce the same socket exception. Removing line 84 produces a PlatformNotSupportedException.

**Comment by michaeluranaka** [comment]
If i remove lines 82, 83, and 86 it works.

**Comment by luigiberrettini** [comment]
Line 82 is not essential and as for line 83 I do not honestly know the reason of the error: both can be disabled on non Windows OSes

Line 86 is related to Windows OS system calls, therefore I should find a replacement for other operating systems

**Comment by michaeluranaka** [comment]
Ahh I see. Thanks for your quick responses!

**Comment by luigiberrettini** [comment]
Created two issues:
https://github.com/dotnet/corefx/issues/28305
https://github.com/dotnet/corefx/issues/28306

**Comment by luigiberrettini** [comment]
The solution is to replace the following code:

```csharp
tcp.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ExclusiveAddressUse, true);
tcp.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.DontLinger, false);
tcp.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Linger, new LingerOption(true, 0));
tcp.Client.IOControl(IOControlCode.KeepAliveValues, keepAlive.ToByteArray(), null);
```

with:

```csharp
tcp.Client.ExclusiveAddressUse = true;
tcp.Client.LingerState = new LingerOption(true, 0);
tcp.Client.KeepAliveState = new KeepAliveOption(keepAliveConfig.Enabled, keepAliveConfig.RetryCount, keepAliveConfig.Timeout, keepAliveConfig.Interval)
```

I will need to use #if directives because:
 - ExclusiveAddressUse is only available on Unix starting from .NET Core 2.1 (#24809)
 - KeepAliveState and KeepAliveOption will be available after https://github.com/dotnet/corefx/issues/25040 is closed

**Comment by luigiberrettini** [comment]
Hi @michaeluranaka it would be nice if you could help me test PR #130 to see if it solves this issue

**Comment by michaeluranaka** [comment]
Hi @luigiberrettini,

Thank you for working on this issue.  I checked out the branch and tried it out and it looks like im still getting the same socket exception:

`2018-04-25 10:21:29.3150 Warn Task faulted Exception: System.Net.Sockets.SocketException (0x80004005): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at NLog.Targets.Syslog.MessageSend.SocketInitializationForOsx.ApplyKeepAliveValues(KeepAliveConfig keepAliveConfig)
   at NLog.Targets.Syslog.MessageSend.SocketInitialization.SetKeepAlive(KeepAliveConfig keepAliveConfig)
   at NLog.Targets.Syslog.MessageSend.Tcp.Setup()
   at NLog.Targets.Syslog.MessageSend.MessageTransmitter.<SendMessageAsync>b__18_0(Task _)
   at NLog.Targets.Syslog.Extensions.TaskExtensions.<>c__DisplayClass0_0`1.<Then>b__0(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)`

**Comment by luigiberrettini** [comment]
Which version of OSX are you using?

**Comment by michaeluranaka** [comment]
10.13.4 High Sierra

**Comment by luigiberrettini** [comment]
Can you post the output of the `system_profiler SPSoftwareDataType` command?

**Comment by michaeluranaka** [comment]
`Software:

    System Software Overview:

      System Version: macOS 10.13.4 (17E199)
      Kernel Version: Darwin 17.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 days 38 minutes`

**Comment by luigiberrettini** [comment]
It seems that the Darwin 17.5.0 supports keepAlive:

- https://opensource.apple.com/source/xnu/xnu-4570.41.2/bsd/netinet/tcp.h.auto.html
- https://opensource.apple.com/source/xnu/xnu-4570.41.2/bsd/netinet/tcp_timer.h.auto.html

It would be really helpful if you can help me find out [wich SetSocketOption](https://github.com/luigiberrettini/NLog.Targets.Syslog/blob/d670680af11f8719d0b02835ec3f924847b0a010/src/NLog.Targets.Syslog/MessageSend/SocketInitializationForOsx.cs#L40-L42) fails

**Comment by michaeluranaka** [comment]
If i take out all 3 lines it works. I tried one by one enabling each line and it seems like all of them are causing the error.

**Comment by luigiberrettini** [comment]
You are right but I do not know why 😞

I've created [some tests](https://github.com/luigiberrettini/CrossPlatformKeepAlive/blob/master/TestSuite.cs) to check if setting socket options related to keep-alive work.
Unfortunately, even if both Linux and OS X kernels supports the option name constants I used, the tests are failing:
 - [Linux](https://travis-ci.org/luigiberrettini/CrossPlatformKeepAlive/jobs/371471364)
 - [OS X](https://travis-ci.org/luigiberrettini/CrossPlatformKeepAlive/jobs/371471365)

**Comment by luigiberrettini** [comment]
Digging into corefx code I found the cause of the behavior you are experiencing is a `TryGetPlatformSocketOption` that returns `false` as detailed below.

Because of this the code for Linux/OS X should be replaced with a NOOP 😞 😡

**1. The public SetSocketOption [calls](https://github.com/dotnet/corefx/blob/v2.0.7/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L1801) an internal SetSocketOption:**
```csharp
public void SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, int optionValue)
{
    //...
    SetSocketOption(optionLevel, optionName, optionValue, false)
    //...
}
```

**2. The internal SetSocketOption [calls](https://github.com/dotnet/corefx/blob/v2.0.7/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L4750) an OS specific SetSockOpt:**
```csharp
internal unsafe void SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, int optionValue, bool silent)
{
    // ...
    errorCode = SocketPal.SetSockOpt(_handle, optionLevel, optionName, optionValue);
    // ...
}
```

**3. The Linux/OS X SetSockOpt [calls](https://github.com/dotnet/corefx/blob/v2.0.7/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L1082) an interop SetSockOpt:**
```csharp
public static unsafe SocketError SetSockOpt(SafeCloseSocket handle, SocketOptionLevel optionLevel, SocketOptionName optionName, int optionValue)
{
    // ...
    err = Interop.Sys.SetSockOpt(handle, optionLevel, optionName, (byte*)&optionValue, sizeof(int));
    // ...
}
```

**4. The interop SetSockOpt is [defined](https://github.com/dotnet/corefx/blob/v2.0.7/src/Common/src/Interop/Unix/System.Native/Interop.SetSockOpt.cs#L14) as:**
```csharp
[DllImport(Libraries.SystemNative, EntryPoint = "SystemNative_SetSockOpt")]
internal static extern unsafe Error SetSockOpt(SafeHandle socket, SocketOptionLevel optionLevel, SocketOptionName optionName, byte* optionValue, int optionLen);
```

**5. The implementation [calls](https://github.com/dotnet/corefx/blob/v2.0.7/src/Native/Unix/System.Native/pal_networking.cpp#L2183) TryGetPlatformSocketOption before making the setsockopt system call:**
```csharp
extern "C"
Error SystemNative_SetSockOpt(intptr_t socket, int32_t socketOptionLevel, int32_t socketOptionName, uint8_t* optionValue, int32_t optionLen)]
{
    // ...
    int optLevel, optName;
    if (!TryGetPlatformSocketOption(socketOptionLevel, socketOptionName, optLevel, optName))
    {
        return PAL_ENOTSUP;
    }
    // ...
    int err = setsockopt(fd, optLevel, optName, optionValue, static_cast<socklen_t>(optionLen));
    // ...
}
```

**6. TryGetPlatformSocketOption [returns false](https://github.com/dotnet/corefx/blob/v2.0.7/src/Native/Unix/System.Native/pal_networking.cpp#L2001)  for all options but PAL_SO_TCP_NODELAY:**
```csharp
static bool TryGetPlatformSocketOption(int32_t socketOptionName, int32_t socketOptionLevel, int& optLevel, int& optName)
{
    switch (socketOptionName)
    {
        // ...
        case PAL_SOL_TCP:
            optLevel = IPPROTO_TCP;

            switch (socketOptionLevel)
            {
                case PAL_SO_TCP_NODELAY:
                    optName = TCP_NODELAY;
                    return true;

                // case PAL_SO_TCP_BSDURGENT:

                default:
                    return false;
            }
        // ...
    }
}
```

**Comment by luigiberrettini** [comment]
I [managed](https://github.com/dotnet/corefx/issues/25040#issuecomment-384656089) to use P/Invoke to set and retrieve socket options: I will use what I did to solve this issue 😉

**Comment by luigiberrettini** [comment]
@michaeluranaka I [managed](https://github.com/dotnet/corefx/issues/25040#issuecomment-384656089) to use P/Invoke to set and retrieve socket options.
I used the same approach in the commit added to PR #131: if you can check that everything is working I can merge it.

**Comment by michaeluranaka** [comment]
Hi @luigiberrettini,

I checked out the changes and it looks like its working now. Thank you for working on this!
